#!/usr/bin/env python
import os
import sys
import subprocess
from importlib import import_module


import flask
# from predictor import main

# disable the WARNING: Do not use the development server in a production environment.
sys.modules['flask.cli'].show_server_banner = lambda *x: None 

app = flask.Flask(__name__)


@app.route('/ping', methods=['GET'])
def ping():
    return flask.Response(response='\n', status=200, mimetype='application/json')

@app.route('/invocations', methods=['POST'])
def invocations():
    return main(flask.request.get_data(cache=False))

if __name__ == '__main__':
    app.run(
        host=os.environ.get('FLASK_RUN_HOST', '0.0.0.0'),
        port=os.environ.get('FLASK_RUN_PORT', 8080)
    )
